CREATE FUNCTION [dbo].[Test_GetKeyNumber]
(
		@TableName nvarchar(max),
        @KeyType varchar(max) = 'PRIMARY KEY',
		@KeyColumn varchar(max) = NULL
)
RETURNS INT
AS
BEGIN
	DECLARE @Result int;
 
	IF @KeyColumn IS NULL
	BEGIN
		SELECT @Result = COUNT(0)
		FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
		WHERE TABLE_NAME = @TableName AND CONSTRAINT_TYPE = @KeyType
	END
	ELSE
	BEGIN
		SELECT @Result = COUNT(0)
		FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS c
		INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE k
		  ON k.TABLE_NAME = c.TABLE_NAME
		  AND k.CONSTRAINT_NAME = c.CONSTRAINT_NAME
		WHERE c.TABLE_NAME = @TableName AND CONSTRAINT_TYPE = @KeyType
	END
	
	RETURN @Result
END


